name: Renovate + Flux Reconcile

on:
  schedule:
    - cron: "0 3 * * 1"  # Every Monday at 3AM UTC
  workflow_dispatch:     # Manual trigger

jobs:
  renovate-flux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Install Flux CLI
        run: |
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux --version

      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          LOG_LEVEL: info
        run: renovate ${{ github.repository }}

      - name: Reconcile Flux
        if: success()   # Only reconcile if Renovate ran successfully
        run: |
          flux reconcile source git flux-system --with-source
