# Renovate Bot GitHub Action Workflow
# This workflow automates dependency updates using Renovate Bot for Flux configurations
# 
# References:
# - Renovate Bot: https://docs.renovatebot.com/
# - GitHub Actions Workflow Syntax: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# - Renovate GitHub Action: https://github.com/renovatebot/github-action
# - Flux CLI: https://fluxcd.io/flux/cmd/

name: Renovate-Bot
# Workflow Triggers
# Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Manual trigger via GitHub UI
  # Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # Scheduled run (every Sunday at 2AM UTC)
  # Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    - cron: '0 2 * * 0' 

jobs:
  generate-flux-manifests:
  # This job ensures we have the latest Flux system manifests before running Renovate
    name: Generate Flux Component YAMLs
    runs-on: ubuntu-latest

    # Only run on master branch to prevent unnecessary executions on feature branches
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
    if: github.ref == 'refs/heads/master' 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }} 
      #Install Flux CLI and generate component manifests
      # Reference: https://fluxcd.io/flux/installation/
      - name: Install Flux CLI and Generate Flux Component Manifests
        run: |
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux --version

  renovate:
    name: Run Renovate on main branch
    runs-on: ubuntu-latest
    # Ensure Flux manifests are generated before running Renovate
    # Reference: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
    needs: generate-flux-manifests
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          # Full history for Renovate
          fetch-depth: 0
          
      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.2
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}  # Critical: specify the repository
          LOG_LEVEL: debug
          RENOVATE_PRINT_CONFIG: "true"
